export const slots = [
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie1',
        age: '3',
        parent: 'Melba1',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie2',
        age: '3',
        parent: 'Melba2',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie3',
        age: '3',
        parent: 'Melba3',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie4',
        age: '3',
        parent: 'Melba4',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie5',
        age: '3',
        parent: 'Melba5',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie6',
        age: '3',
        parent: 'Melba6',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie7',
        age: '3',
        parent: 'Melba7',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie8',
        age: '3',
        parent: 'Melba8',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie9',
        age: '3',
        parent: 'Melba9',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie10',
        age: '3',
        parent: 'Melba10',
        phone: '1222',
        email: 'macki@gmail.com',
    },
    {
        date: '11/12/23',
        time: '19:30 AM',
        name: 'Mackie11',
        age: '3',
        parent: 'Melba11',
        phone: '1222',
        email: 'macki@gmail.com',
    },
]
